### ISSUE TITLE
SQLite does not support JSONFields.

### ISSUE THREAD

**Issue by luffy7272** [dongfanger/teprunner-backend#1]
请问下 有遇到这个问题吗（Python 3.8.7）
(venv) D:\workspace\teprunner-backend>python manage.py migrate
SystemCheckError: System check identified some issues:

ERRORS:
user.Role: (fields.E180) SQLite does not support JSONFields.

**Comment by luffy7272** [comment]
https://github.com/Singosgu/GreaterWMS/issues/13

**Comment by luffy7272** [comment]
已解决
https://github.com/Singosgu/GreaterWMS/issues/13

**Comment by dongfanger** [comment]
好的，sqlite3.dll替换下应该就可以了。
